### ISSUE TITLE
Restore Atomist's list of labels on issues in this repository

### ISSUE THREAD

**Issue by jessitron** [atomist/sdm-smoke-test#3]
Ben, I think this repository was created at an inopportune time. Most of the labels aren't available in 'create issue'. I wanted to add "bug". Do you have a way to replace the labels for this one repo?

![screen shot 2018-03-31 at 11 39 19 am](https://user-images.githubusercontent.com/1149737/38165402-49f626fc-34d8-11e8-9144-3aacde82eac6.png)

**Comment by jessitron** [comment]
I tested repository creation and new repos are getting the labels. It's just this one.
It was created with `create sdm` a few days ago.

**Comment by whostolebenfrog** [comment]
@jessitron There was a window where I had to disable the label creation stuff - this repo was created then so that matches up with your findings.

In the short term if you add a repo webhook for this repo in the team you need the labels populating for: that will trigger a re-import of the labels.

I'll create an issue for catching up the repos that arrived in that window (24 hours approx) as we're not tracking that yet.

Thanks.
